### ISSUE TITLE
haxe 4 rc1

### ISSUE THREAD

**Issue by postite** [benmerckx/image#3]
hello ..
image does not compile with haxe rc1 :

/Users/ut/haxe/haxe_libraries/image/0.1.1/github/684da0fb40c4972d2066138501ad655198785780/src/image/Image.hx:168: characters 5-6 : Unexpected >
The terminal process terminated with exit code: 1

its too imbricated for me to resolve this error.

**Comment by benmerckx** [comment]
I bet this would be resolved when rewriting this promises. I'll try to have a look at it

**Comment by benmerckx** [comment]
I updated the lib to use Promises. Since the last version was pretty stable on Haxe 3 I don't see the need to keep Haxe 3 support around. There's some more code cleanup I'd like to do after which I'll release, but it should work at this point. Thanks for your PR!

**Comment by postite** [comment]
great !! thx
